# .github/workflows/deploy_bq_to_firestore_weather.yml
#
# Deploy the BigQuery to Firestore daily weather exporter Cloud Run Function
#
# Copyright (c) 2025 Caden Howell (cadenhowell@gmail.com)
# Developed with assistance from ChatGPT 4o (2025) and Google Gemini 2.5 Pro (2025).
# Apache 2.0 Licensed as described in the file LICENSE

name: Deploy BQ to Firestore Weather Exporter

on:
  # Trigger the workflow on push events
  push:
    branches:
      - main
    paths:
      # Only run when files in the function's directory change
      - 'functions/bq_to_firestore_daily_weather/**'
      # Also run if this workflow file itself changes
      - '.github/workflows/deploy_bq_to_firestore_weather.yml'

jobs:
  deploy:
    # These permissions are required for secure OIDC authentication with Google Cloud
    permissions:
      contents: 'read'
      id-token: 'write'

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        id: auth
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: '${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}'
          service_account: '${{ secrets.GCP_SERVICE_ACCOUNT_EMAIL_FUNCTIONS }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: 'Delete existing function to ensure clean deployment'
        run: |
          gcloud functions delete bq-to-fs-weather-exporter --region=us-central1 --quiet || true

      - name: 'Deploy Gen2 Cloud Function'
        run: gcloud functions deploy bq-to-fs-weather-exporter --gen2 --region=us-central1 --runtime=python311 --source=./functions/bq_to_firestore_daily_weather/src --entry-point=export_weather_to_firestore --trigger-http --no-allow-unauthenticated --service-account=${{ secrets.GCP_SERVICE_ACCOUNT_EMAIL_BQ_TO_FS_WEATHER_RUNTIME }}