# .github/workflows/deploy_sensor_monitor.yml

name: Deploy Sensor Status Monitor Function

on:
  # Trigger the workflow on push events to the main branch
  push:
    branches:
      - main
    paths:
      # Only run when files in the function's directory change
      - 'functions/sensor_status_monitor/**'
      # Also run if this workflow file itself changes
      - '.github/workflows/deploy_sensor_monitor.yml'
      # Also if certain Terraform files are updated
      - 'terraform/iam_deploy_cloud_run_functions.tf'
      - 'terraform/iam_workload_identity_pool.tf'

jobs:
  deploy:
    # These permissions are required for secure OIDC authentication with Google Cloud
    permissions:
      contents: 'read'
      id-token: 'write'

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Debug service account email
        run: |
          echo "Using service account: ${{ secrets.GCP_SERVICE_ACCOUNT_EMAIL_FUNCTIONS }}"

      - name: Authenticate to Google Cloud
        id: auth
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: '${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}'
          service_account: '${{ secrets.GCP_SERVICE_ACCOUNT_EMAIL_FUNCTIONS }}'
          token_format: 'access_token'

# For debugging OIDC Tokens
#
#      - name: Output GitHub OIDC Token Claims
#        shell: bash
#        run: |
#          echo "${ACTIONS_ID_TOKEN_REQUEST_TOKEN}" | cut -d '.' -f2 | base64 -d | jq
#        continue-on-error: true
#        env:
#          ACTIONS_ID_TOKEN_REQUEST_TOKEN: ${{ steps.auth.outputs.id_token }}

      - name: Print gcloud identity
        run: gcloud auth list

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'
        with:
          version: '>= 530.0.0'

      - name: 'Use gcloud CLI'
        run: 'gcloud info'

      - name: 'Deploy Gen2 Cloud Function'
        env:
          RUNTIME_SERVICE_ACCOUNT: ${{ secrets.GCP_SERVICE_ACCOUNT_EMAIL_RUNTIME }}
        run: |
          gcloud functions deploy sensor-status-monitor-function \
            --gen2 \
            --region=us-central1 \
            --runtime=python311 \
            --source=./functions/sensor_status_monitor/src \
            --entry-point=process_sensor_status \
            --trigger-topic=sun-sensor-ingest-topic \
            --service-account=function-runtime@sunlight-sensor.iam.gserviceaccount.com

