# .github/workflows/deploy_rest_sensor_api.yml
#
# Deploy the REST to Pub/Sub proxy Cloud Run Function
#
# Copyright (c) 2025 Caden Howell (cadenhowell@gmail.com)
# Developed with assistance from ChatGPT 4o (2025) and Google Gemini 2.5 Pro (2025).
# Apache 2.0 Licensed as described in the file LICENSE

name: Deploy REST to Pub/Sub Proxy Function

on:
  # Trigger the workflow on push events to the main branch
  push:
    branches:
      - main
    paths:
      # Only run when files in the function's directory change
      - 'functions/rest_sensor_api_to_pubsub/**'
      # Also run if this workflow file itself changes
      - '.github/workflows/deploy_rest_sensor_api.yml'

jobs:
  deploy:
    # These permissions are required for secure OIDC authentication with Google Cloud
    permissions:
      contents: 'read'
      id-token: 'write'

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        id: auth
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: '${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}'
          service_account: '${{ secrets.GCP_SERVICE_ACCOUNT_EMAIL_FUNCTIONS }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: 'Deploy Gen2 Cloud Function'
        run: |
          gcloud functions deploy rest-to-pubsub-proxy-function \
            --gen2 \
            --region=us-central1 \
            --runtime=python311 \
            --source=./functions/rest_sensor_api_to_pubsub/src \
            --entry-point=proxy_to_pubsub \
            --trigger-http \
            --allow-unauthenticated \
            --service-account=${{ secrets.GCP_SERVICE_ACCOUNT_EMAIL_SENSOR_PROXY_RUNTIME }} \
            --set-env-vars=GCP_PROJECT=${{ steps.auth.outputs.project_id }},TOPIC_ID=sun-sensor-ingest-topic,SECRET_BEARER_TOKEN=${{ secrets.SENSOR_API_BEARER_TOKEN }}