# .github/workflows/deploy_sensor_monitor.yml
#
# Deploy the sensor status monitor Cloud Run Function
#
# Copyright (c) 2025 Caden Howell (cadenhowell@gmail.com)
# Developed with assistance from ChatGPT 4o (2025), Google Gemini 2.5 Pro (2025) and Claude Sonnet 4 (2025).
# Apache 2.0 Licensed as described in the file LICENSE

name: Deploy Sensor Status Monitor Function

on:
  # Trigger the workflow on push events to the main branch
  push:
    branches:
      - main
    paths:
      # Only run when files in the function's directory change
      - 'functions/sensor_status_monitor/**'
      # Also run if this workflow file itself changes
      - '.github/workflows/deploy_sensor_monitor.yml'
      # Also if certain Terraform files are updated
      - 'terraform/iam_deploy_cloud_run_functions.tf'
      - 'terraform/iam_workload_identity_pool.tf'

jobs:
  deploy:
    # These permissions are required for secure OIDC authentication with Google Cloud
    permissions:
      contents: 'read'
      id-token: 'write'

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        id: auth
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: '${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}'
          service_account: '${{ secrets.GCP_SERVICE_ACCOUNT_EMAIL_FUNCTIONS }}'
          token_format: 'access_token'
          create_credentials_file: true

#      - name: 'Debug authentication and service accounts'
#        run: |
#          echo "=== Current gcloud configuration ==="
#          gcloud config list
#          echo "=== Current authenticated account ==="
#          gcloud auth list --format="value(account)"
#          echo "=== Available service accounts in project ==="
#          gcloud iam service-accounts list
#          echo "=== Testing if runtime service account exists ==="
#          gcloud iam service-accounts describe ${{ secrets.GCP_SERVICE_ACCOUNT_EMAIL_RUNTIME }} || echo "Runtime SA not found"
#          echo "=== Project number ==="
#          gcloud projects describe $(gcloud config get-value project) --format="value(projectNumber)"

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'
        with:
          version: '>= 530.0.0'

      - name: 'Use gcloud CLI'
        run: 'gcloud info'

      - name: 'Deploy Gen2 Cloud Function'
        env:
          CLOUDSDK_AUTH_CREDENTIAL_FILE_OVERRIDE: ${{ steps.auth.outputs.credentials_file_path }}
          RUNTIME_SERVICE_ACCOUNT: ${{ secrets.GCP_SERVICE_ACCOUNT_EMAIL_RUNTIME }}
        run: |
          gcloud functions deploy sensor-status-monitor-function \
            --gen2 \
            --region=us-central1 \
            --runtime=python311 \
            --source=./functions/sensor_status_monitor/src \
            --entry-point=process_sensor_status \
            --trigger-topic=sun-sensor-ingest-topic \
            --service-account=$RUNTIME_SERVICE_ACCOUNT \
            --set-env-vars="ALERT_EMAIL_ADDRESS=${{ secrets.ALERT_EMAIL_ADDRESS }},GMAIL_USER=${{ secrets.GMAIL_USER }},GMAIL_APP_PASSWORD=${{ secrets.GMAIL_APP_PASSWORD }},PUSHOVER_APP_TOKEN=${{ secrets.PUSHOVER_APP_TOKEN }},PUSHOVER_USER_KEY=${{ secrets.PUSHOVER_USER_KEY }}" \
            --verbosity=debug