# .github/workflows/deploy_cassandra_latest_readings.yml
#
# Deploy the Cassandra Latest Readings Cloud Run Function
#
# Copyright (c) 2025 Caden Howell (cadenhowell@gmail.com)
# Developed with assistance from Claude Sonnet 4.5 (2025).
# Apache 2.0 Licensed as described in the file LICENSE

name: Deploy Cassandra Latest Readings Function

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'functions/cassandra_latest_readings/**'
      - '.github/workflows/deploy_cassandra_latest_readings.yml'

jobs:
  deploy:
    env:
      TERM: linux

    permissions:
      contents: 'read'
      id-token: 'write'

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        id: auth
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: '${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}'
          service_account: '${{ secrets.GCP_SERVICE_ACCOUNT_EMAIL_FUNCTIONS }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: 'Create deployment flags file'
        env:
          ASTRA_CLIENT_ID: ${{ secrets.ASTRA_CLIENT_ID }}
          ASTRA_CLIENT_SECRET: ${{ secrets.ASTRA_CLIENT_SECRET }}
          BUNDLE_BUCKET: ${{ secrets.GCP_PROJECT_ID }}-cassandra-bundle
          SERVICE_ACCOUNT: ${{ secrets.GCP_SERVICE_ACCOUNT_EMAIL_CASSANDRA_READER }}
        run: |
          cat > /tmp/deploy-flags.yaml << EOF
          --gen2:
          --region: us-central1
          --runtime: python311
          --source: ./functions/cassandra_latest_readings/src
          --entry-point: get_latest_readings
          --trigger-http:
          --allow-unauthenticated:
          --service-account: ${SERVICE_ACCOUNT}
          --set-env-vars:
            ASTRA_CLIENT_ID: ${ASTRA_CLIENT_ID}
            ASTRA_CLIENT_SECRET: ${ASTRA_CLIENT_SECRET}
            ASTRA_SECURE_BUNDLE_BUCKET: ${BUNDLE_BUCKET}
            ASTRA_KEYSPACE: sunlight_data
          --timeout: 60s
          --memory: 256Mi
          EOF

      - name: 'Deploy Gen2 Cloud Function'
        run: |
          gcloud functions deploy cassandra-latest-readings \
            --flags-file=/tmp/deploy-flags.yaml